# Generated by Django 4.1.7 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('ryear', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
