# Generated by Django 4.1.7 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=12)),
                ('subj', models.CharField(max_length=3)),
                ('adate', models.DateField()),
            ],
            options={
                'db_table': 'attend',
            },
        ),
        migrations.AddConstraint(
            model_name='attend',
            constraint=models.UniqueConstraint(fields=('regno', 'subj', 'adate'), name='key'),
        ),
    ]
